/*
 * MainFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  __USER__
 */
public class MainFrm extends javax.swing.JFrame {

	/** Creates new form MainFrm */
	public MainFrm() {
		initComponents();
		//设置最大 化
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		table = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu3 = new javax.swing.JMenu();
		jmiProductTypeAdd = new javax.swing.JMenuItem();
		jmiProductTypeModify = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		jmiProductAdd = new javax.swing.JMenuItem();
		jmiProductModify = new javax.swing.JMenuItem();
		jmiExit = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem6 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u8d2d\u7269\u7cfb\u7edf\u4e3b\u754c\u9762");

		jMenu1.setIcon(new javax.swing.ImageIcon(
				"./images\\base.png")); // NOI18N
		jMenu1.setText("\u57fa\u672c\u6570\u636e\u7ef4\u62a4");

		jMenu3.setIcon(new javax.swing.ImageIcon(
				"./images\\manager.gif")); // NOI18N
		jMenu3.setText("\u5546\u54c1\u79cd\u7c7b\u7ba1\u7406");

		jmiProductTypeAdd.setIcon(new javax.swing.ImageIcon(
				"./images\\add.png")); // NOI18N
		jmiProductTypeAdd.setText("\u5546\u54c1\u7c7b\u522b\u6dfb\u52a0");
		jmiProductTypeAdd
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jmiProductTypeAddActionPerformed(evt);
					}
				});
		jMenu3.add(jmiProductTypeAdd);

		jmiProductTypeModify.setIcon(new javax.swing.ImageIcon(
				"./images\\modify.gif")); // NOI18N
		jmiProductTypeModify.setText("\u5546\u54c1\u7c7b\u522b\u7ef4\u62a4");
		jmiProductTypeModify
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jmiProductTypeModifyActionPerformed(evt);
					}
				});
		jMenu3.add(jmiProductTypeModify);

		jMenu1.add(jMenu3);

		jMenu4
				.setIcon(new javax.swing.ImageIcon(
						"./images\\product manager.gif")); // NOI18N
		jMenu4.setText("\u5546\u54c1\u7ba1\u7406");

		jmiProductAdd.setIcon(new javax.swing.ImageIcon(
				"./images\\shopadd.gif")); // NOI18N
		jmiProductAdd.setText("\u5546\u54c1\u6dfb\u52a0");
		jmiProductAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiProductAddActionPerformed(evt);
			}
		});
		jMenu4.add(jmiProductAdd);

		jmiProductModify.setIcon(new javax.swing.ImageIcon(
				"./images\\modify.gif")); // NOI18N
		jmiProductModify.setText("\u5546\u54c1\u7ef4\u62a4");
		jmiProductModify.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiProductModifyActionPerformed(evt);
			}
		});
		jMenu4.add(jmiProductModify);

		jMenu1.add(jMenu4);

		jmiExit.setIcon(new javax.swing.ImageIcon(
				"./images\\exit.png")); // NOI18N
		jmiExit.setText("\u9000\u51fa\u7cfb\u7edf");
		jmiExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiExitActionPerformed(evt);
			}
		});
		jMenu1.add(jmiExit);

		jMenuBar1.add(jMenu1);

		jMenu2.setIcon(new javax.swing.ImageIcon(
				"./images\\about.png")); // NOI18N
		jMenu2.setText("\u5173\u4e8e\u6211\u4eec");

		jMenuItem6.setIcon(new javax.swing.ImageIcon(
				"./images\\me.png")); // NOI18N
		jMenuItem6.setText("\u5173\u4e8e\u7f51\u7ad9");
		jMenu2.add(jMenuItem6);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jmiProductModifyActionPerformed(java.awt.event.ActionEvent evt) {
		ProductManageInterFrm ProductManageInterFrm = new ProductManageInterFrm();
		ProductManageInterFrm.setVisible(true);
		this.table.add(ProductManageInterFrm);
	}

	private void jmiProductAddActionPerformed(java.awt.event.ActionEvent evt) {
		ProductAddInterFrm ProductAddInterFrm = new ProductAddInterFrm();
		ProductAddInterFrm.setVisible(true);
		this.table.add(ProductAddInterFrm);
	}

	private void jmiProductTypeModifyActionPerformed(
			java.awt.event.ActionEvent evt) {
		ProductTypeManageInterFrm ProductTypeManageInterFrm = new ProductTypeManageInterFrm();
		ProductTypeManageInterFrm.setVisible(true);
		this.table.add(ProductTypeManageInterFrm);
	}

	private void jmiProductTypeAddActionPerformed(java.awt.event.ActionEvent evt) {
		ProductTypeInterFrm productTypeInterFrm = new ProductTypeInterFrm();
		productTypeInterFrm.setVisible(true);
		this.table.add(productTypeInterFrm);
	}

	private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {
		int result = JOptionPane.showConfirmDialog(null, "是否退出系统");
		if (result == 0) {
			this.dispose();//观看它的传值然后定义变量
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jmiExit;
	private javax.swing.JMenuItem jmiProductAdd;
	private javax.swing.JMenuItem jmiProductModify;
	private javax.swing.JMenuItem jmiProductTypeAdd;
	private javax.swing.JMenuItem jmiProductTypeModify;
	private javax.swing.JDesktopPane table;
	// End of variables declaration//GEN-END:variables

}