server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stufood?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver





